### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by psolymos** [borealbirds/GNM#1]
- [x] Check that we have all the bird data (Atlas updates, BU/WildTrax, etc)
- [x] Use 100 km^2 buffer around BCRs and compile all bird data with offsets, save as bundles
- [x] Bundle predictors and raster stacks by buffered BCR for prediction and intersect for modeling
- [x] Finalize predictor sets for BCRs
- [x] Finalize BRT code (1 species in 1 BCR) [possibly extending by bootstrap]
- [x] Develop HPC code to run on Graham (check timings and RAM usage)
- [x] Deploy data and run models on Graham and collect results (species by BCR, no bootstrap for now)

**Comment by psolymos** [comment]
Testing Slack integration...

**Comment by psolymos** [comment]
@dstralberg and @psolymos discussed GNMs today for the Feb 2019 sprint:

- will include: vegetation, climate, terrain wetness, agr/urb (not yearly layers)
- will not include year as covariate
- use layers at native resolution, but resample to 1 km^2 for prediction
- will check mean/SD of layers in each BCR to filter out constant ones
- subsample by time period and SS: single set to be used on 10-fold XV (no bootstrap for now)
